language: node_js
node_js:
  - 0.12

env:
  - TRAVIS=true

git:
  depth: 1
  submodules: false

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:ci && npm run coverage:check
